### ISSUE TITLE
Problem with version 1.1.3

### ISSUE THREAD

**Issue by marwin1991** [angrymeir/SecScanner2JUnit#32]
```
$ ss2ju sast gl-sast-report.json gl-sast-report.xml .gitlab/ss2ju-config.yml
Traceback (most recent call last):
  File "/usr/local/bin/ss2ju", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/secscanner2junit/__init__.py", line 50, in main
    ss2ju_config = get_config()
                   ^^^^^^^^^^^^
TypeError: get_config() missing 1 required positional argument: 'path'
Uploading artifacts for failed job
```

@angrymeir

**Comment by marwin1991** [comment]
We call `get_config()` without argument:

```
    if args.config:
        ss2ju_config = get_config()
 ```

should be changed to 

```
    if args.config:
        ss2ju_config = get_config(args.config)
````

@angrymeir  ?

**Comment by angrymeir** [comment]
Yes, ah that's what I was talking about with the testing blind spots...Guess I'll create CI stage, that builds the package and executes tests on the entire software in addition to Unit-tests
