### ISSUE TITLE
With Python 3.8.5 getting TypeError upon execution

### ISSUE THREAD

**Issue by mattysan** [angrymeir/SecScanner2JUnit#35]
**Describe the bug**
Can't execute ss2ju at all with Python 3.8.5, even with "--help" argument. Getting a TypeError as shown below

**Steps to reproduce**

1. Swap to Python 3.8.5
2. Execute `ss2ju --help` or any valid command line
3. Receive TypeError: 'type' object is not subscriptable

I tried this with Python 3.9.12 and it worked as expected.

**Expected behavior**
Proper execution. In this case, show command line args.

**Additional context/Screenshots**

Traceback (most recent call last):
  File "/Users/mfa0434/.pyenv/versions/3.8.5/bin/ss2ju", line 5, in <module>
    from secscanner2junit import main
  File "/Users/mfa0434/.pyenv/versions/3.8.5/lib/python3.8/site-packages/secscanner2junit/__init__.py", line 9, in <module>
    from secscanner2junit.config import get_config, Config
  File "/Users/mfa0434/.pyenv/versions/3.8.5/lib/python3.8/site-packages/secscanner2junit/config.py", line 19, in <module>
    class Config:
  File "/Users/mfa0434/.pyenv/versions/3.8.5/lib/python3.8/site-packages/secscanner2junit/config.py", line 20, in Config
    def __init__(self, suppressions: list[Suppression]):
TypeError: 'type' object is not subscriptable

**Comment by marwin1991** [comment]
@mattysan you need to use python 3.10 :)

**Comment by angrymeir** [comment]
@mattysan Thanks for pointing that out! I forgot to update the python version in _pyproject.toml_, will do so later :)
